version: "2"

services:
  worker_1:
    build:
      context:
        ./docker/nginx/worker
    tty: true
    volumes:
      - ./web:/web

  worker_2:
    build:
      context:
        ./docker/nginx/worker
    tty: true
    volumes:
      - ./web:/web

  worker_3:
    build:
      context:
        ./docker/nginx/worker
    tty: true
    volumes:
      - ./web:/web

  worker_proxy:
    build:
      context: ./docker/nginx/load_balancer
    ports:
      - 80:80
    links:
      - worker_1
      - worker_2
      - worker_3
